//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mehr.Installer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mehr.Installer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arabic {
            get {
                object obj = ResourceManager.GetObject("Arabic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap English {
            get {
                object obj = ResourceManager.GetObject("English", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در هنگام اتصال بانک اطلاعاتی.
        /// </summary>
        internal static string ErrorWhileAttachingDataBase {
            get {
                return ResourceManager.GetString("ErrorWhileAttachingDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در هنگام ساخت پوشه نصب برنامه ، ممکن است مسیر انتخاب شده موجود نبوده و یا خطای دسترسی رخ داده باشد.
        /// </summary>
        internal static string ErrorWhileCreateNewMehrDirectory {
            get {
                return ResourceManager.GetString("ErrorWhileCreateNewMehrDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در حین نصب بانک اطلاعاتی.
        /// </summary>
        internal static string ErrorWhileInstallingSqlserver {
            get {
                return ResourceManager.GetString("ErrorWhileInstallingSqlserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در هنگام نصب نرم افزار.
        /// </summary>
        internal static string ErrorWhileInstallMehr {
            get {
                return ResourceManager.GetString("ErrorWhileInstallMehr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصورتیکه برای اولین بار است که اقدام  به نصب میکنید پیشنهاد میگردد تنظیمات در حالت پیش فرض باقی بماند.
        /// </summary>
        internal static string InstallKindComment {
            get {
                return ResourceManager.GetString("InstallKindComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصورتیکه قبلا از نرم افزار استفاده و اقدام به تعویض ویندوز نموده اید و پوشه قبلی موجود است،گزینه &quot;اتصال به پوشه قبلی&quot; را انتخاب نمایید ..
        /// </summary>
        internal static string InstallKindComment1 {
            get {
                return ResourceManager.GetString("InstallKindComment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر نصب برنامه انتخاب نشده است.
        /// </summary>
        internal static string InstallPathNotInsertError {
            get {
                return ResourceManager.GetString("InstallPathNotInsertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات نصب با موفقیت انجام شد.
        /// </summary>
        internal static string InstallSuccessfulMsg {
            get {
                return ResourceManager.GetString("InstallSuccessfulMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MehrLogo {
            get {
                object obj = ResourceManager.GetObject("MehrLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mehr {0}.
        /// </summary>
        internal static string MehrTitle {
            get {
                return ResourceManager.GetString("MehrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام سرور بانک اطلاعاتی یک نام دلخواه است و می بایست غیر تکراری باشد ..
        /// </summary>
        internal static string NewInstanceComment {
            get {
                return ResourceManager.GetString("NewInstanceComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصورتیکه نرم افرار مهر از قبل بر روی سیستم شما نصب نیست ، پیشنهاد میشود به حالت پیش فرض (MehrSqlServer) باقی بماند.
        /// </summary>
        internal static string NewInstanceComment1 {
            get {
                return ResourceManager.GetString("NewInstanceComment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محل نصب انتخاب شده می بایست خالی باشد.
        /// </summary>
        internal static string NewMehrPathMustBeEmptyError {
            get {
                return ResourceManager.GetString("NewMehrPathMustBeEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک یا چند سرور بانک اطلاعاتی بر روی سیستم شما نصب که می توانید انتخاب نمایید و از نصب مجدد خودداری کنید ..
        /// </summary>
        internal static string OldInstanceComment {
            get {
                return ResourceManager.GetString("OldInstanceComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر نصب پوشه قبلی انتخاب نشده است.
        /// </summary>
        internal static string OldMehrPathNotSelectedError {
            get {
                return ResourceManager.GetString("OldMehrPathNotSelectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر پوشه قبلی انتخاب شده اشتباه است . فایل دیتا بیس یافت نشد ..
        /// </summary>
        internal static string OldPathWrongDataNotfountError {
            get {
                return ResourceManager.GetString("OldPathWrongDataNotfountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Persian {
            get {
                object obj = ResourceManager.GetObject("Persian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام سرور بانک اطلاعاتی تکراری است و هم اکنون بر روی سیستم نصب است..
        /// </summary>
        internal static string SameInstanceNameErr {
            get {
                return ResourceManager.GetString("SameInstanceNameErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی در حین عملیات نصب رخ داده است.
        /// </summary>
        internal static string SomeErrorRunWhileInstallationError {
            get {
                return ResourceManager.GetString("SomeErrorRunWhileInstallationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام سرور بانک اطلاعاتی وارد نشده است ..
        /// </summary>
        internal static string SqlInstanceNotInsertErr {
            get {
                return ResourceManager.GetString("SqlInstanceNotInsertErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در هنگام استخراج فونت ها.
        /// </summary>
        internal static string UnzipFontsFileError {
            get {
                return ResourceManager.GetString("UnzipFontsFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در هنگام استخراج فایل های نصب نرم افزار.
        /// </summary>
        internal static string UnzipMehrFileError {
            get {
                return ResourceManager.GetString("UnzipMehrFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در هنگام استخراج فایل نصب بانک اطلاعاتی.
        /// </summary>
        internal static string UnzipSql64FileError {
            get {
                return ResourceManager.GetString("UnzipSql64FileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال استخراج فایل های نصب ....
        /// </summary>
        internal static string WhileExtractMehrFileText {
            get {
                return ResourceManager.GetString("WhileExtractMehrFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال استخراج فایل های نصب بانک اطلاعاتی ....
        /// </summary>
        internal static string WhileExtractSqlFileText {
            get {
                return ResourceManager.GetString("WhileExtractSqlFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نصب نرم افزار.
        /// </summary>
        internal static string WhileInstallMehrFileText {
            get {
                return ResourceManager.GetString("WhileInstallMehrFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نصب بانک اطلاعاتی.
        /// </summary>
        internal static string WhileInstallSqlFileText {
            get {
                return ResourceManager.GetString("WhileInstallSqlFileText", resourceCulture);
            }
        }
    }
}
